### ISSUE TITLE
Data is lost if we lose connection to the server

### ISSUE THREAD

**Issue by MokeEire** [mdewey131/Snappa-Scoreboard#15]
When connection to the server is lost, all game data is lost.

### Potential solutions
- push each score/round to SnappaDB and check with users about any unfinished games upon app startup
- create temp local file which can be uploaded at startup

**Comment by MokeEire** [comment]
Increased the idle timeout (from 15 mins to 30 mins), does this fix the issue?

**Comment by mdewey131** [comment]
Mercifully, finally, fixed in ae1117c
