### ISSUE TITLE
Validate scoring options

### ISSUE THREAD

**Issue by MokeEire** [mdewey131/Snappa-Scoreboard#19]
A player should only be about to score one non-paddle on their offensive round.

Offensive players should not be able to score against themselves with a paddle.

**Comment by mdewey131** [comment]
This is a WIP at the moment. I've managed to fix the second issue in my current branch but the first one still doesn't have a solution. I was working through a solution and I think that the easiest way to refer back to past shooters would be to use the values that we're going to generate when we fix #20, so the two issues are linked
