### ISSUE TITLE
Reorder/Clean DB table columns

### ISSUE THREAD

**Issue by MokeEire** [mdewey131/Snappa-Scoreboard#22]
@mdewey131 let me know if you agree with these change suggestions, or if you would prefer different table formats

## `game_stats_players`

1. remove `player_team` because `team` is the column being populated
2. Change shots from `int` to `dbl` (double precision in PostgreSQL)
2. Reorder to the following format:

| game_id | player_id | team | total_points | paddle_points |ones |twos |threes |impossibles |points_per_round |shots |off_ppr |def_ppr |toss_efficiency|
|--|--|--|--|--|--|--|--|--|--|--|--|--|--|
|int|int|chr|int|int|int|int|int|int|dbl|dbl|dbl|dbl|dbl|

## `scores`

1. Reorder to following format:

|score_id| game_id | player_id | scoring_team | round_num | points_scored |shooting| paddle|
|--|--|--|--|--|--|--|--|
|int|int|int|chr|chr|int|lgl|lgl|

**Comment by mdewey131** [comment]
I agree with these changes. I've made the changes to data types and removed `player_team`. Currently,  I'm working on ordering the columns which does not have a straightforward implementation in postrgres.

**Comment by mdewey131** [comment]
All changes have been applied as suggested here
