### ISSUE TITLE
Support for up to 4v4 

### ISSUE THREAD

**Issue by mdewey131** [mdewey131/Snappa-Scoreboard#3]
Currently the scoreboard only supports 2v2, while games usually go up to 4v4 or are often unbalanced. Making the first 2 players on each team necessary and the other 2 unnecessary would solve the issue

**Comment by MokeEire** [comment]
Potentially changing games table to:

|game_id|player_id|
|-------------|--------------|
|1|1|
|1|2|
|...|...|
|1|n_players|

Or was that another table?

**Comment by mdewey131** [comment]
Yes, game_stats records players in each game so it will scale as you've written it here.

**Comment by MokeEire** [comment]
Fixed [here](https://github.com/mdewey131/Snappa-Scoreboard/commit/1d041cfd8cf57b93ae2fc3de2409feb66a00d018#diff-1e678274602e250345bb25d52e7c2d76)
