### ISSUE TITLE
Shots are overestimated

### ISSUE THREAD

**Issue by mdewey131** [mdewey131/Snappa-Scoreboard#33]
Currently, the database records one more shot for the winning team than they actually took, which is a consequence of the way that ending a game upon hitting "pass the dice" has worked in the past. 

This issue is fixed in the branch [refine_live_update](https://github.com/mdewey131/Snappa-Scoreboard/tree/refine_live_update) but still persists on existing data.

**Comment by MokeEire** [comment]
@mdewey131 This is fixed recently, right?

**Comment by mdewey131** [comment]
Yes, so this issue was originally fixed, but twice, which meant that scores ended up being underestimated by one. That issue is fixed with 2297b8624688c5ea38a5a2560d8f7d1930e61b60
