### ISSUE TITLE
Passing the first round when no one has scored causes the app to crash

### ISSUE THREAD

**Issue by mdewey131** [mdewey131/Snappa-Scoreboard#35]
This is an issue that I have noticed when no one score in round 1A. The app crashes because it attempts to make `player_stats`  as a roll-up of a non-existent `scores` table. I fixed this in the current master file (see commit d2db469) but could probably be done in a more elegant fashion than just passing `invisible()`

**Comment by MokeEire** [comment]
I believe this is fixed somewhere? @mdewey131

**Comment by mdewey131** [comment]
Oh yes, this is fixed actually
