### ISSUE TITLE
Only show unfinished games which have scored a single point

### ISSUE THREAD

**Issue by MokeEire** [mdewey131/Snappa-Scoreboard#36]
Currently if we start a game and exit, the server still asks if we want to continue the previous 0-0 game.  Instead, just discard 0-0 games.

**Comment by mdewey131** [comment]
I can handle this one

**Comment by MokeEire** [comment]
sweet jesus the speed!

**Comment by mdewey131** [comment]
Sometimes it helps to have Slack open while you're doing other things ¯\_(ツ)_/¯
