### ISSUE TITLE
Game Start times are not tracked correctly 

### ISSUE THREAD

**Issue by mdewey131** [mdewey131/Snappa-Scoreboard#48]
This is no longer an issue on game input, meaning we will no longer see this error for new data, with 94b74609d47b7a4b14b80e821d9dcae3083ae2c2. However, on the database, most `game_start` values are in UTC while most `game_end` times are in PST. We should make this consistent. I've changed the data input to record values in PST, so it makes sense to change all previous `game_start` values to PST as well

**Comment by MokeEire** [comment]
Got acquainted with Postgres timezones and fixed this on March 26th
