### ISSUE TITLE
App will be stuck on waiter endlessly if teams are not in the Markov chain model

### ISSUE THREAD

**Issue by mdewey131** [mdewey131/Snappa-Scoreboard#52]
Whenever users try to access the `win probabilities` page, they will encounter a pretty serious error if one of the teams is not within the record. Because there's no error handling for those teams, the waiter will wait endlessly for a result that will never come, effectively locking players out of the game. I'm going to fix this by including an entry for the "average team", i.e. a generic entry for teams of the same size. That way, everyone can access win probabilities at all times

**Comment by MokeEire** [comment]
This is fixed with markov_guardrails branch?

**Comment by mdewey131** [comment]
Ah, yes, this is fixed with b26c95daf4a3b68658400c7e31cf98b76b698dea
